# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IRC News
email: contact@ircnews.net
description: > # this means to ignore newlines until "baseurl:"
  IRC development news and links
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ircnews.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: IRCLinks
github_username:  ircnews
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
